apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-a123456 # name of the ConfigMap, we will reference this
#in the deployment
  namespace: sandbox
  labels:
    user: a123456
data:
  index.html: <h1>Hello Omar!</h1> # the name of the file we want to save
#and what the contents of that file will be
