
#deploy a sample web server in the sandbox namespace with label user
apiVersion: apps/v1 #change according to what is current
kind: Deployment
metadata:
  name: hello-web-a123456
  namespace: default
  labels:
    user: o719580
spec:
  replicas: 1
  selector:
    matchLabels:
      user: o719580
   template:
     metadata:
       labels:
         user: o719580
     spec:
       containers:
       - name: nginx
         image: nginx
         ports:
         - containerPort: 80