apiVersion: v1
kind: Secret
metadata:
  name: tomcat-user-a123456
  namespace: default
  labels:
  user: a123456
type: Opaque
data:
  TOMCAT_USERNAME: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: tomcat-pass-a123456
  namespace: sandbox
  labels:
  user: a123456
type: Opaque
data:
  TOMCAT_PASSWORD: cGFzc3dvcmQ=
